/**
 * generated by baekjun-ts-support
 */
const readline = require("readline");

// CODE START
/**
 *
 * @param {String[]} inputs
 */
const main = (inputs) => {
  console.log(inputs);
};
// CODE END

const /** @type{string[]} */ chunks = [];
const reader = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

reader.on("line", (line) => chunks.push(line.trim()));
reader.on("close", () => {
  main(chunks);
});
