/**
 * generated by baekjun-ts-support
 */
import readline from "readline";

const chunks: string[] = [];
const reader = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

// CODE START
const main = (inputs: string[]) => {
  console.log(inputs);
};
// CODE END

reader.on("line", (line) => chunks.push(line.trim()));
reader.on("close", () => {
  main(chunks);
});
